name: Appium CI
on:
    workflow_dispatch:
        inputs:
          PLATFORM:
             description: 'Platform name'
             required: true
             default: 'android'
             type: choice
             options:
               - android
               - ios

jobs:
   build:
     runs-on: macos-latest # the machine type
     strategy: # we are using strategy if we need to run on parallel with different devices and version
       matrix:
         api-level: [32] #Google api level for example [25,23,28] 
         target: [default]
     steps:
     
     - uses: actions/checkout@v2 #checkout the code 
     
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     
     - name: Install and Run Appium Server
       run: |
         chmod +x ./ci-scripts/RunAppiumServer.sh # install and run appium server in the background
         ./ci-scripts/RunAppiumServer.sh
     
     - name: Set Platform Name if Android
       if: ${{ github.event.inputs.PLATFORM != 'android' }}
       run: export PLATFORM=android
       
     - name: Set Platform Name if iOS
       if: ${{ github.event.inputs.PLATFORM != 'ios' }}
       run: export PLATFORM=ios
     
     - name: Run Appium Tests
       uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
       with:
         api-level: ${{ matrix.api-level }}
         target: ${{ matrix.target }}
         arch: x86_64
         profile: Pixel_5_API_32
         script: mvn -Dtest=TestSuite test # running our test with info to check the results
