name: Android Appium Tests
on:
  workflow_dispatch

env: 
 PLATFORM: android

jobs:
   build:
     runs-on: macos-latest # the machine type
     steps:
     
     - uses: actions/checkout@v3 #checkout the code 
     
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: '11'
     
     - name: Install and Run Appium Server
       run: |
         chmod +x ./ci-scripts/RunAppiumServer.sh # install and run appium server in the background
         ./ci-scripts/RunAppiumServer.sh
       
     - name: Set up Android Emulator and Run Appium Tests
       uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
       with:
         api-level: 30
         target: default
         arch: x86_64
         profile: Nexus 6
         disable-animations: false
         force-avd-creation: false
         script: export PLATFORM=Android; gradle testAndroid
