name: Android Appium Tests
on:
  workflow_dispatch

env: 
 PLATFORM: android

jobs:
   build:
     runs-on: macos-latest # the machine type
     steps:
     
     - uses: actions/checkout@v2 #checkout the code 
     
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     
     - name: Install and Run Appium Server
       run: |
         chmod +x ./ci-scripts/RunAppiumServer.sh # install and run appium server in the background
         ./ci-scripts/RunAppiumServer.sh
       
     - name: Set up Android Emulator and Run Appium Tests
       uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
       with:
         api-level: 30
         target: default
         arch: x86_64
         profile: Nexus 6
         script: mvn -Dtest=TestSuite test
